ElectronicShop_v0.4/Controllers/AddDeviceController.cs
using ElectronicShop_v0._4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectronicShop_v0._4.Controllers
{
    public class AddDeviceController : Controller
    {
        // GET: AddDevice
        [HttpGet]
        public ActionResult AddDevice()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddDevice(Products device)
        {
            var db = new ElectronicShopContext();

            var checkDevice = db.Products.Select(x => x.name == device.name).FirstOrDefault();

            List<string> categoryList = new List<string>
            {
                "Computer and Tablets", 
                "Headphones",
                "Monitors",
                "Mouse and keyboards",
                "Video game consoles"
            };         

            bool isStringContainedInList = categoryList.Contains(device.category);

            if (isStringContainedInList == true)
            {
                if (checkDevice == false)
                {
                    db.Products.Add(device);
                    db.SaveChanges();
                    ViewBag.Succes = "Product has been added";
                    return View();
                }
                else
                {
                    ViewBag.Error = "This item already exist";
                    return View();
                }
            }
            else
            {
                ViewBag.Error = "You have to choose one category from the list: Computer and Tablets, Headphones, Monitors, Mouse and keyboards, Video game consoles";
                return View();
            }
        }

        [HttpGet]
        public ActionResult LogInEmployee()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogInEmployee(Employees checkEmployee)
        {
            var db = new ElectronicShopContext();

            var isEmployeeMatch = db.Employees.Where(x => x.userName == checkEmployee.userName &&
                                                           x.password == checkEmployee.password).FirstOrDefault();
            bool adminCheck = isEmployeeMatch.position.StartsWith("admin");

            if (adminCheck == true)
            {

                if (isEmployeeMatch != null)
                {
                    Session["SessionEmployee"] = isEmployeeMatch;
                    Session.Timeout = 15;
                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ViewBag.Error = "Wrong username or password";
                }
                return View();
            }
            else
            {
                if (isEmployeeMatch != null)
                {
                    ViewBag.Error = "Welcome, if you want to make a order you have to create a customer account";
                }
                else
                {
                    ViewBag.Error = "Wrong username or password";
                }
                return View();
            }
        }

    }
}

ElectronicShop_v0.4/Controllers/CustomerRegisterController.cs
using ElectronicShop_v0._4.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;
//using System.Web.HttpContext.Current.Session;


namespace ElectronicShop_v0._4.Controllers
{
    public class CustomerRegisterController : Controller
    {
        // GET: CustomerRegister
        [HttpGet]
        public ActionResult CustomerRegister()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CustomerRegister(Customers newCustomer)
        {
            var db = new ElectronicShopContext();

            var checkCustomer = db.Customers.Select(x => x.nickName == newCustomer.nickName).FirstOrDefault();
            var checkCustomerMail = db.Customers.Select(x => x.emailAdress == newCustomer.emailAdress).FirstOrDefault();

            if (checkCustomer == false && checkCustomerMail == false)
            {
                db.Customers.Add(newCustomer);
                db.SaveChanges();
                ViewBag.Succes = "Customer has beed created";
                return View();
            }
            else if(checkCustomerMail != false)
            {
                ViewBag.Error = "This email adress is being used";
                return View();
            }
            else
            {
                ViewBag.Error = "This nickname is being used";
                return View();
            }
        }

        [HttpGet]
        public ActionResult LogIn()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult LogIn(Customers checkCustomer)
        {
            var db = new ElectronicShopContext();

            var isCustomerMatch = db.Customers.Where(x => x.nickName == checkCustomer.nickName 
                                      && x.password == checkCustomer.password).FirstOrDefault();
            

            if (isCustomerMatch != null)
            {
                Session["SessionCustomer"] = isCustomerMatch;
                Session.Timeout = 15;
                return RedirectToAction("ShowCustomerProfile", "CustomerRegister");                
            }
            else
            {    
                ViewBag.Error = "Wrong nickname or password";
            }
            return View();
        }


        public ActionResult ShowCustomerProfile()
        {
            var customerProfile = Session["SessionCustomer"];    
            
            return View(customerProfile);
        }


        public ActionResult ShowCustomerOrders()
        {
            var db = new ElectronicShopContext();

            var customerProfile =  (Customers)Session["SessionCustomer"];
            var cutomerOrdersList = db.CustomerOrders.Where(x => x.customerID == customerProfile.customerID).ToList();                 

            return View(cutomerOrdersList);
        }

    }
}

ElectronicShop_v0.4/Views/CustomerRegister/CustomerRegister.cshtml
@model ElectronicShop_v0._4.Models.Customers

@{
    ViewBag.Title = "Creating customer account";
}

<h2>Creating customer account</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Creating customer account</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nickName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nickName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nickName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.emailAdress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.emailAdress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.emailAdress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.phoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.phoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.phoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.confirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.confirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.confirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to homepage", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ElectronicShop_v0.4/Views/CustomerRegister/LogIn.cshtml
@model ElectronicShop_v0._4.Models.Customers

@{
    ViewBag.Title = "LogIn";
}

<h2>Log In</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Customers</h4>
        <div>
            @ViewBag.Error
        </div>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.nickName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nickName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nickName, "", new { @class = "text-danger" })
            </div>
        </div>




        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.confirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.confirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.confirmPassword, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Log in" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Back to homepage", "Index", "Home")</li>
        <li>@Html.ActionLink("Register", "CustomerRegister", "CustomerRegister")</li>
        <li>@Html.ActionLink("Employee", "LogInEmployee", "AddDevice")</li>
    </ul>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ElectronicShop_v0.4/Views/CustomerRegister/ShowCustomerOrders.cshtml
@model IEnumerable<ElectronicShop_v0._4.Models.CustomerOrders>

@{
    ViewBag.Title = "CustomerOrders";
}
<h2>Customer Orders</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.productID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.customerID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.productName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.amount)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.productID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.customerID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.productName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.amount)
        </td>
        <td>
            @Html.ActionLink("Details", "Details", new { id=item.orderID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.orderID })
        </td>
    </tr>
}

</table>

ElectronicShop_v0.4/Views/CustomerRegister/ShowCustomerProfile.cshtml
@model ElectronicShop_v0._4.Models.Customers

@{
    ViewBag.Title = "CustomerProfile";
}

<h2>Customer Profile</h2>

<div>
    <h4>Customer Profile</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.nickName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nickName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.emailAdress)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.emailAdress)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.phoneNumber)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.phoneNumber)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Order list", "ShowCustomerOrders", "CustomerRegister") |
    @Html.ActionLink("Back to homepage", "Index", "Home")
</p>